#!/usr/bin/env python

from optparse import OptionParser
import os, subprocess

usage = "usage: %prog [options] folder_name\n\nExample:\n       %prog -c athabasca_2011 bootstrap"
parser = OptionParser(usage=usage)
parser.add_option("-c", "--client", dest="client", default=False,
                  help="eg: nonfiction")
parser.add_option("-t", "--target-host",
                  action="store", dest="target", default='www.tb.nonwebdev.com',
                  help="default: www.tb.nonwebdev.com",
                  metavar="HOSTNAME")
parser.add_option("-u", "--user",
                  action="store", dest="user",
                  metavar="USERNAME")


(options, args) = parser.parse_args()

if not options.target or not options.client:
  print 'hostname and client name must be supplied'
  parser.print_usage()
  exit()
  

if len(args) != 1:
  print 'No folder name supplied'
  parser.print_usage()
  exit()

folder_name = args[0]
folder_name = os.path.abspath(folder_name) + '/'

if not os.path.isdir(folder_name):
  print 'Not a folder: ' + folder_name
  parser.print_usage()
  exit()

if options.user:
  user = options.user
else:
  user = os.popen('whoami').read().strip()

target = '%s@%s:/var/www/clients/%s/' % (user, options.target, options.client)
command = ['rsync', '-avz', '--exclude', 'README*', '--chmod=ugo+rwx,o-w' ,folder_name, target]

if subprocess.call(command):
  print 'success!'