#!/bin/sh

username=your_username
host=www.target.server.com
client=client_foldername

recess --compress less/bootstrap.typography.less > bootstrap.typography.css
recess --compress less/bootstrap.less > bootstrap.min.css

scp *.css $username@$host:/var/www/clients/$client/public_html/stylesheets/